NLnetLabs/octseq

Cargo.toml, src/traits.rs, src/types.rs
This PR removes the three additional trait bounds `AsRef<[u8]>`, `AsMut<[u8]>`, and `Sized` from `OctetsBuilder`.
This was already partially done in the domain version, but I realized it might be useful to drop `AsRef<[u8]>`, too. Now you can have a write-only octets builder without any ability to look back – specifically, anything `io::Write` can now be an octets builder.
Users can signal their need for more functionality such as `AsRef<[u8]>` or even `AsMut<[u8]>` by explicitly stating those trait bounds, thus ruling out certain builders.
=> Drop additional trait bounds from OctetsBuilder.

src/lib.rs, src/str.rs
This PR adds a new module `str` with two types `Str<Octets>` and `StrBuilder<Octets>` which are equivalents to `str` and `String` using generic octet sequences or octet builders as their data storage. Method and impl sets aren’t quite equivaent yet, but the types are already rather useful.
=> Add Str and StrBuilder.

src/traits.rs, src/types.rs
This PR allows implementations of `OctetsFrom` and `OctetsInto` to choose their own error type. The primary motivation is to allow types where the conversion can’t fail to use `Infallible` and provide variations of the conversion methods that then simply don’t fail.
Thus, the PR also prefixes the names of the primary methods of the two traits with `try_` and adds new `try_`-less methods that are only available when conversion can’t fail.
=> Make OctetsFrom and OctetsInto have associated error types.

src/parse.rs
This will make it possible to enrich the type later without needing a breaking change.
=> Turn parse::ShortInput into a newtype of ().

src/parse.rs
This PR adds a method `Parser::parse_parser` that allows parsing a given number of octets and return them as a cloned parser.
=> Add Parser::parse_parser.

src/parse.rs
For routecore we need these three things. If we agree this should be in octseq, I'll add tests. Perhaps the IpAddr parsers can be in bit more efficient.
=> Add parse functions for large integer types.

src/builder.rs
This PR restricts the value of `OctetsBuilder::BuildError<E>` to always be `Into<ShortBuild<E>>`. In practice this means it’s either `E` or `ShortBuild<E>`. This is necessary to allow nested octets builder (i.e., octets builders that wrap other octets builders) because you cannot enforce this sort of thing via trait bounds – you’d need non-lifetime higher ranked trait bounds for it.
=> Restrict options for OctetsBuilder::BuildError<E>.

src/array.rs, src/builder.rs, src/str.rs
This PR drops the attempt at being clever from the error handling of `OctetsBuilder` in favor of a very straightforward strategy.
=> Simplify octets builder error handling.

src/array.rs, src/builder.rs, src/str.rs
This PR moves the `freeze` method out of `OctetsBuilder` into a new `FreezeBuilder` trait. This allows octets builders that are not actually freezable, for instance temporarily wrapping an octets builder around a mutable reference to some other octets builder.
=> Split FreezeBuilder out of OctetsBuilder.

src/octets.rs
This PR limits the `Error` associated type of `OctetsFrom` and `OctetsInto` in the same way as `OctetsBuilder` is already limited: to `Into<ShortBuf>`. This avoids a bunch of complicated trait bounds for users of the traits.
=> Limit the error type of OctetsFrom and OctetsInto.

src/array.rs
This PR implements the `Octets` trait for `Array<N>` which for some inexplicable reason was missing.
=> Implement Octets for Array<N>.

src/builder.rs
This PR adds blanket implementations for `OctetsBuilder` and `Truncate` for mutable references of types that are `OctetsBuilder` and `Truncate`, respectively.
=> Add blanked impls for ref muts of Octetsbuilder and Truncate.

src/array.rs
This PR adds a new method `Array::resize_raw` that changes the size of the octets sequence inside and array without updating the content.
Note that this isn’t unsafe because the array is properly initialized. The content may just be surprising …
=> Add Array::resize_raw.

src/parse.rs
This PR renames the methods on `Parser` that parse integers by adding a `_be` suffix to make clear that they are parsing integers in big-endian byte order and adds new methods for little endian parsing.
This is a breaking change.
Fixes #34.
=> Make byte order in integer parsing explicit.

src/builder.rs
This PR adds a type alias to refer to the `AppendError` of an octets type’s associated builder. Instead of having to write:
```
fn build<Octs>() -> Result<Octs, <<Octs as FromBuilder>::Builder as OctetsBuilder>::AppendError> { todo!() }
```
you can now just write
```
fn build<Octs>() -> Result<Octs, BuilderAppendError<Octs>> { todo!() }
```
=> Add an BuilderAppendError type alias.

src/parse.rs
When creating a new `Parser` by calling `.parse_parser(some_len)` on an existing `Parser`, the new parser has a limited view over the same octets as the old parser. This limit (`self.len`) was however not respected by the `peek_all()` method, possibly returning an unexpectedly large slice.
=> Limit peek_all to return data up until self.len

src/octets.rs
For &'a <[u8] as Oct>, range(&'b self, ...) get an Oct reference with lifetime 'a instead of 'b, so it's possible to do something as following:
```
let mut name: Dname<&[u8]> = ...;
loop {
if let Some(p) = name.parent() {
name = p; // here p is not borrow from name, but the octets inside.
}
}
```
=> fix lifetime for &Oct::Range

src/parse.rs
This PR introduces a new constructor for `Parser`, similar to the existing `fn from_ref` but taking a range to initialize the parser on a subset of the octets.
It currently errors when the end of the passed range lies beyond the end of the octets, meaning passing in an open-ended range `(n..)` is not possible. Alternatively, we could accept any (open) end and limit it to the length of the octets, and not returning any error.
=> Introduce with_range on Parser

Cargo.toml, src/lib.rs
`bytes` has a default `std` feature, preventing `no_std` usage.
=> Fix `no_std`.

src/octets.rs, src/parse.rs, src/str.rs
This PR implements some changes suggested by Clippy. As a result, it actually provides an implementation of `OctetsFrom` for `Smallvec` (which was presented but never compiled due to a broken cfg attribute). It also removes the `Borrow<[u8]>` impls for `Str<_>` and `StrBuilder<_>` due to conflicts with the `Hash` impl.
Because of the latter, this is a breaking change.
=> Various Clippy-suggested fixes and some fallout from that.

src/str.rs
This PR impls `OctetsFrom` for `Str<_>` which somehow was missing.
=> Impl OctetsFrom for Str.

src/str.rs
This PR adds two functions, `try_copy_from_str` and `copy_from_str` to `Str<_>` that create a new octets sequence with the content of a `str`.
=> Add [try_]copy_from_str to Str<_>.

src/array.rs
The `new_len` parameter to Array::resize_raw() is the new length of the contained octets sequence. The documentation for resize_raw() specifies that it is an error for `new_len` to be larger than the array size, but the current code also returns an error if `new_len` is equal to the array size.
The following code will cause a panic with octseq 0.5.2, for instance if one were preparing an Array<512> buffer to receive a UDP DNS query message into.
```rust
use octseq::{array::Array, EmptyBuilder};
const UDP_DNS_QUERY_MAX_SIZE: usize = 512;
fn main() {
let mut query_packet = Array::<UDP_DNS_QUERY_MAX_SIZE>::empty();
query_packet.resize_raw(UDP_DNS_QUERY_MAX_SIZE).unwrap();
}
```
=> Fix Array::resize_raw() to allow resizing to the length of the array.
